/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.pattern.analyzator;

import org.surmon.pattern.api.analysis.Analysis;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.event.MouseInputAdapter;

/**
 *
 * @author palasjiri
 */
public class AnalysisItemView extends javax.swing.JPanel {
    
    private final Analysis analysis;
    
    /**
     * Creates new form AnalysisItemView
     */
    public AnalysisItemView(final Analysis analysis) {
        this.analysis = analysis;
        initComponents();
        
        titleTF.setText(analysis.getTitle());
        titleTF.addMouseListener(new MouseInputAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getClickCount() == 2){ // is double click
                    titleTF.setEnabled(true);
                }
            }
            
        });
        
        titleTF.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                analysis.setTitle(titleTF.getText());
                titleTF.setEnabled(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        titleTF.setText(org.openide.util.NbBundle.getMessage(AnalysisItemView.class, "AnalysisItemView.titleTF.text")); // NOI18N
        titleTF.setBorder(null);
        titleTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        titleTF.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
