/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.pattern.analyzator;

import java.util.List;
import javax.swing.JPanel;
import org.surmon.pattern.api.analysis.Analysis;

/**
 * Displays list of analyses user performed.
 * 
 * @author palasjiri
 */
public class AnalysisListView extends JPanel {

    /**
     * Creates new form AnalysisListView
     */
    public AnalysisListView() {   
        initComponents();
    }
    
    public void update(List<Analysis> aList){
        removeAll();
        for (Analysis analysis : aList) {
            AnalysisItemView iv = new AnalysisItemView(analysis);
            add(iv);
        }
        revalidate();
        repaint();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
